#!/bin/sh

#Scripts/GitHooks/pre-commit
#
#Attempt builds and tests before committing to develop or stable
#
#Copyright(C) 2018, Ivan Tobias Johnson
#
#LICENSE: MIT License

branch=$(git rev-parse --abbrev-ref HEAD)

#0 = pass; 1 = soft fail; 2 = hard fail
code=0

if [ "$branch" == "stable" ] || [ "$branch" == "develop" ]; then
	echo "Building..."
	VALID_BUILD=$(make -j all > /dev/null; echo $?)
	echo "Testing..."
	VALID_TEST=$([ "$VALID_BUILD" = 0 ] && make -j test > /dev/null; echo $?)
	if [ "$branch" == "stable" ]; then
		code=1
		echo "#In general, you shouldn't commit directly to the stable branch!"

		if [ "$VALID_BUILD" != "0" ]; then
			code=2
			echo "#THIS COMMIT DOES NOT COMPILE!"
			echo "UNDER NO CIRCUMSTANCES SHOULD YOU COMMIT THIS TO THE STABLE BRANCH!"
		elif [ "$VALID_TEST" != "0" ]; then
			echo "#This commit does not pass all tests!"
		fi
	elif [ "$branch" == "develop" ]; then
		if [ "$VALID_BUILD" != "0" ]; then
			code=2
			echo "#THIS COMMIT DOES NOT COMPILE!"
			echo "You *REALLY* shouldn't commit this to the develop branch!"
		elif [ "$VALID_TEST" != "0" ]; then
			code=1
			echo "#This commit does not pass all tests!"
			echo "Please fix them before committing to the develop branch!"
		fi
	fi
fi

[ "$code" = "1" ] &&
	echo "(To override this rejection, use \"git commit --no-verify\")"
exit $code
